### ISSUE TITLE
Feature Request: Trigger macro for each trigger

### ISSUE THREAD

**Issue by rinnocenti** [grandseiken/foundryvtt-multilevel-tokens#19]
instead of a single macro being triggered, it will be possible to have a macro (and args) for each of the 3 phases (Leave, enter and move), so we can set a very variable set of macros. instead of having to check in the macro which trigger was fired.

**Comment by grandseiken** [comment]
Although it's not ideal, you could get the same result with three different drawings stacked on top of each other (one for each event). Since there are two alternatives (that and checking the variable), and I worry that the feature request would end up complicating the UI quite a lot, I am probably not going to look into this any time soon, sorry!
