### ISSUE TITLE
Issue with the Furnace module

### ISSUE THREAD

**Issue by spacegiant** [grandseiken/foundryvtt-multilevel-tokens#24]
When using Multilevel Tokens and the Furnace I see this...
![image](https://user-images.githubusercontent.com/599280/95190166-cb42be00-07c6-11eb-81bd-b144e52bdb39.png)
There has also been some weird form data appearing...
![image](https://user-images.githubusercontent.com/599280/95190630-8a977480-07c7-11eb-804b-eea135fd1650.png)
![image](https://user-images.githubusercontent.com/599280/95190695-9f740800-07c7-11eb-9da7-a13c78e12341.png)

Can be fixed by one of the following: 
- Deactivate the Furnace module
- Deactivate the Furnace's Advanced Drawing tools in module settings.

Note: the weird data added remains when the Furnace is deactivated.

**Comment by grandseiken** [comment]
Hey spacegiant,

As far as I know all of these issues are not actually the fault of Multilevel Tokens, but are compatibility issues caused by other modules you're using not being fully updated for the 0.7.x beta release of Foundry yet.

The double UI is due to this issue with Furnace: https://github.com/kakaroto/fvtt-module-furnace/issues/62
The issue with weird data and commas I am not sure about but I believe it is caused by better rolls 5e, are you using that module?

Generally a lot of modules don't work properly with 0.7.3 yet and can cause weird issues. Multilevel tokens on its own is actually fine as far as I know.

**Comment by spacegiant** [comment]
@grandseiken Thanks for the info. (And apologies for not stating which version of Foundry I was on). That makes perfect sense. I'll keep an eye on the ticket you linked to. :)
