### ISSUE TITLE
Token Clones speaking

### ISSUE THREAD

**Issue by Madzapple** [grandseiken/foundryvtt-multilevel-tokens#30]
Whenever I talk on my one map that uses token cloning, the speech of the token comes from the clone.  It throws us into a wall of fog of war.  Any tips or is this an ongoing issue?

**Comment by grandseiken** [comment]
The speech bubble actually comes out of _both_ of the tokens, this is an intentional (optional) feature of the module. However, that can be a bit awkward if you have the foundry pan-to-speaker option turned on. Maybe I shouldn't enable this feature by default.

You options are:
1) Disable the **Pan to Token Speaker** in the Foundry core settings. Then chat bubbles will pop out of both the token and its clones, but won't have any panning.
2) Disable the **Auto-sync chat bubbles** setting in the Multilevel Tokens module settings. Then you'll only have chat bubbles pop out of the token you have selected, but the canvas will still pan to it.
