### ISSUE TITLE
Position of cloned tokens in rotated areas has an offset

### ISSUE THREAD

**Issue by manuelVo** [grandseiken/foundryvtt-multilevel-tokens#44]
When a clone area is rotated the position of the cloned tokens have an offset in the area from the position of the original token.

Steps to reproduce:
1. Create two clone areas of same size. One has rotation set to 0, the other has rotation set to 90. Make sure they are bot aligned to the grid.
2. Put a token into one of the areas.
3. The cloned token will not have the same position as the original token, but will be misaligned by an offset. The picture below illustrates such a situation. Note how the cloned token reaches quite far into the neighboring cell even though the original token is perfectly aligned to the grid.
![An image showing the misalignment of the cloned token](https://user-images.githubusercontent.com/1705157/100157026-309f5b00-2eaa-11eb-9b61-409e69a7fcfe.png)

Foundry VTT Version: 0.7.7
Multilevel Tokens Version: 1.3.4

**Comment by jvilders** [comment]
Adding to this, the same occurs if using either of the mirroring option checkboxes in the configuration of the target shape (horizontal/vertical mirroring). I would guess that this is because rotating the shapes and using these options both rely on the same underlying process.
Tested on Foundry VTT version: 0.7.9, Multilevel Tokens Version 1.3.4

**Comment by grandseiken** [comment]
This was the same issue as https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/74, fixing now
