### ISSUE TITLE
Feature suggestion: Masking areas that are ignored for teleportation and token cloning

### ISSUE THREAD

**Issue by CDeenen** [grandseiken/foundryvtt-multilevel-tokens#50]
I currently have a map consisting of 2 levels: a big circular room (CR) with a floating platform (FP) in the center. I currently clone CR onto FP, since anyone standing on FP can see down into CR. However, if a token in CR moves under the platform, it is still being cloned onto FP, as if they're standing on top of the platform.
It would be great if you could draw another shape that you could use to mask the region, so cloning doesn't happen if a token is moved into that region.

I'd also love to be able to teleport tokens from FP to CR when they fall off the platform. This could also be done quite easily if you create a teleport region to cover the whole map, but mask the platform, so teleportation only happens once a token is moved outside of the masked area.

**Comment by jvilders** [comment]
Functionality for this would be cool, but I think it's more a feature request for the shape drawing tool in base Foundry (being able to free draw shapes and add "holes"). Either way though, I don't think you need it for your situation just yet: You can make both the source teleport region (circular room) and the target teleport region (floating platform) out of 2 half-donut shapes (using the free shape option) instead of 1 enclosed circle. This way the target teleport region is never _on_ the floating platform itself, so no weird projections "from below". You're then also free to add a second same-shape source teleport region around the floating platform (but not on it) that teleports people to a target region down below to simulate falling.

I made the assumption the floating platform is circular like the room. If not, it'll still work, but the two half-shapes you'll need to draw just won't be donuts anymore.

**Comment by grandseiken** [comment]
You can also actually use the polygon tool to make a single (roughly) circular donut shape with a hole in the middle, if you draw out a shape that's like the letter "C" but where the ends come all the way round to join up - this will work how you'd want it to.

**Comment by CDeenen** [comment]
Thanks for the responses. I already tried granseikens suggestion yesterday, but I must've messed up. It didn't work back then, but I just tried again and now it does work.
There's one thing I noticed though: If you have the donut shape on the upper level, but a rectangular or circular shape on the bottom (that's big enough to fit the whole area), any token that's on the bottom floor in the center of the donut will still be cloned on the upper level, even though it's outside of the cloning target area.
You can of course copy the donut shape to the bottom area, which does work, but it might be nice to add a check to see if the cloned token is actually within the target area. Makes it slightly easier to create the shapes. But it's not really a big issue, so no worries :).
