### ISSUE TITLE
Version 0.8.X

### ISSUE THREAD

**Issue by KaiZano** [grandseiken/foundryvtt-multilevel-tokens#87]
I was simply wondering if an update was coming for 0.8.X if the module is not compatible. I've been too scared of losing modules that are as important as this one by updating now instead of waiting for the official release.

**Comment by illandril** [comment]
I have tried this module in 0.8.5, and it doesn't work. I did spend a few minutes checking to see if I could quickly throw together a pull request to give 0.8.x support so I could start using 0.8.x sooner... but it turned out to be too much work than I have time for.

A lot of the hook arguments changed (fairly easy to fix), and a lot of the data types inside maps changed... both things this module uses a lot.

**Comment by whinis** [comment]
Just noticed this issue as well as I prepare for a game tonight, oh well manual move for now.

**Comment by grandseiken** [comment]
Hasn't been updated for 0.8.x yet but hope to get it done in the next few days.

**Comment by KaiZano** [comment]
Great!

Thanks for the fast answer

**Comment by MerionLial** [comment]
Fantastic news!

Don't feel rushed, I think we're all happy that a 0.8 is coming and don't mind waiting a bit.

**Comment by grandseiken** [comment]
See https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/89
