### ISSUE TITLE
Update for compatibility with 0.8.x

### ISSUE THREAD

**Issue by schlosrat** [grandseiken/foundryvtt-multilevel-tokens#89]
Hi, this module is really fantastic and a huge help in my games. Is there plan to update it for 0.8.x? When I enable this module by itself I get a bunch of errors in a world where some of my scenes are already using Multilevel Tokens

![image](https://user-images.githubusercontent.com/50781429/120225019-7dc20800-c212-11eb-95e8-c7d283956c36.png)

**Comment by grandseiken** [comment]
Coming soon

**Comment by Jonwh25** [comment]
Here's another one.

![image](https://user-images.githubusercontent.com/60674327/120399786-8e957b00-c2f1-11eb-97a7-e514c866d7a7.png)

**Comment by grandseiken** [comment]
I can't promise everything works 100% yet, I need to do a bit more testing before I release properly, but if you install manually using the develop branch (`https://raw.githubusercontent.com/grandseiken/foundryvtt-multilevel-tokens/develop/module.json`) I think it's mostly working. If you run into any issues with that one let me know

**Comment by grandseiken** [comment]
1.5.0 is out - please post in this issue if you encounter any problems.

**Comment by Jonwh25** [comment]
Looks like the errors went away.  Just leaving a warning. Not a big deal since it is just a warning and won't have to be updated for a while. Thank you for the quick turn around. This module is pretty amazing :)

![image](https://user-images.githubusercontent.com/60674327/120555864-8a7c6280-c3b0-11eb-9e90-425836c4fd5c.png)
