### ISSUE TITLE
Feature suggestion: Bounding Box

### ISSUE THREAD

**Issue by anathemamask** [grandseiken/foundryvtt-multilevel-tokens#9]
New style item: Bounding box.

Perhaps with a special drawing tool just for it, or just @bound on the box.

Any tokens entering cannot leave- moving to the edge from inside teleports the token to the opposite side of the bound box. 

Use case: spatial magic effects, or just preventing overambitious players from running outside a GM's intended play area prematurely.

**Comment by grandseiken** [comment]
I suppose you could achieve roughly the same effect by adding a pair of `@inout` regions at the top and bottom, and another pair at the left and right? It sounds cool, but is the primary motivation here convenience, or is there something that doesn't work about that?

I thought to myself "that'd be cool, and also I could do bounding boxes that just stop you from leaving rather than wrapping around" before realising that was kind of just a worse way to do walls 🤣

**Comment by kevincox** [comment]
What is the advantage over one-way invisible walls? Just that you get warped back? If you just want that you can also implement it with two boxes as mentioned.
